# This file was generated by GoReleaser. DO NOT EDIT.
class Peek < Formula
  desc "Peek into large files"
  homepage ""
  version "0.0.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/jonomuller/peek/releases/download/v0.0.3/peek_0.0.3_Darwin_x86_64.tar.gz"
    sha256 "eac717dc40e27d831f140be4aa7386cbfa3788b58de8dba09607881e2865a058"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/jonomuller/peek/releases/download/v0.0.3/peek_0.0.3_Linux_x86_64.tar.gz"
      sha256 "050e48becad01f96ce48e32dca6a6bbae5b5a10899734730e1dee0f1a4b6d0ba"
    end
  end

  def install
    bin.install "peek"
  end
end
